### ISSUE TITLE
[Feat] api 작성 

### ISSUE THREAD

**Issue by irupa94** [baedal-project/baedal#2]
## :bulb: 이슈 내용
- 더미데이터를 들여올때 맞는 테이블 작성

## :white_check_mark: 작업 내용
- [x] member
- [x] store
- [x] item 

## :rotating_light: 주의 사항
- erd대로 작성할것

## ERD
![image](https://user-images.githubusercontent.com/5901912/202434831-113ef75f-0a46-42a9-8389-687b528c1635.png)

**Comment by celinaym** [comment]
<img width="828" alt="스크린샷 2022-11-21 오전 12 34 58" src="https://user-images.githubusercontent.com/113876596/202911079-50e00e17-623f-4bbc-b58e-7a7de2c40b20.png">
ERD 이렇게 바꾸려고 하는데 괜찮으신가요? Member 1명당 여러개의 주소를 작성할 수 있되 따로 연관관계를 맺지 않고 embed만 할 생각입니다.
