### ISSUE TITLE
[Bug] 1000명이 Store조회시 서버 다운되는 현상

### ISSUE THREAD

**Issue by Puri12** [baedal-project/baedal#33]
**버그를 설명하세요.**
어떤 버그인지에 대한 명확하고 간결한 설명

**재현 방법**
재현하기 위해 다음의 절차로 진행:

1. Jmeter로 1000명이 동시에 52만개의 Store데이터를 조회
2. sql에러 없이 서버가 다운되는 현상이 있음

**기대하는 동작**
서버 다운되는 원인을 명확하게 찾아야함
1000명 이상 조회 시 다운되지 않도록 구조적으로 개선 필요

**Comment by Puri12** [comment]
## 해결 방법

1. #32 쿼리 최적화
2. #34 캐시서버로 DB접근 줄이기

**Comment by celinaym** [comment]
'jmeter issue'와 내용이 유사해서 jmeter issue는 close하고 여기에 comment 남기도록 하겠습니다.

**Comment by Puri12** [comment]
> 'jmeter issue'와 내용이 유사해서 jmeter issue는 close하고 여기에 comment 남기도록 하겠습니다.

넵!!

**Comment by Puri12** [comment]
## 해결완료
#34 Spring 캐시와 #46 페이징 처리를 통해서 해결
