### ISSUE TITLE
[Docs] 기준 설정 논의

### ISSUE THREAD

**Issue by celinaym** [baedal-project/baedal#7]
## :bulb: 이슈 내용
- 해당 이슈의 내용과 기대되는 결과를 적어주세요.

## :white_check_mark: 작업 내용
- [ ] ES 검색 기준 설정 필요 : 음식 카테고리 별, 후기 좋은 순, 가까운 음식점 등등
- [ ] 후기 좋은 순 등의 기준을 추가할 거면 ERD, API 변경 필요
- [ ] 데이터 처리할 때 측정 기준 필요 

## :rotating_light: 주의 사항
- 작업 시 주의할 사항을 적어주세요.

**Comment by celinaym** [comment]
ES 후기 좋은 순 검색 기준 추가(ERD 수정 필요)

**Comment by irupa94** [comment]
후기 좋은 순서가 평점을 말씀하시는 걸까요?

**Comment by Puri12** [comment]
## :thinking:  의견

### Spring SOP를 이용한 시간측정법
```java
@Slf4j
@Aspect
@Component
public class ExecutionTimer {

    // 조인포인트를 어노테이션으로 설정
    @Pointcut("@annotation(com.aop.annotation.ExeTimer)")
    private void timer(){};

    // 메서드 실행 전,후로 시간을 공유해야 하기 때문
    @Around("timer()")
    public void AssumeExecutionTime(ProceedingJoinPoint joinPoint) throws Throwable {

        StopWatch stopWatch = new StopWatch();

        stopWatch.start();
        joinPoint.proceed(); // 조인포인트의 메서드 실행
        stopWatch.stop();

        long totalTimeMillis = stopWatch.getTotalTimeMillis();

        MethodSignature signature = (MethodSignature) joinPoint.getSignature();
        String methodName = signature.getMethod().getName();

        log.info("실행 메서드: {}, 실행시간 = {}ms", methodName, totalTimeMillis);
    }
}
```

위 방법을 이용해서 커스텀 어노테이션을 생성하면 아래와 같이 메소드 수행에 대한 시간값이 나옴

![image](https://user-images.githubusercontent.com/5901912/202774318-c591992e-edc2-4c01-8294-ec2daeb41f45.png)

이 방법을 사용해서 개선되는 부분을 체크할 수 있지 않을까 생각합니다.
